version: '3.9'
services:
  front:
    image: bizgpt/${PROJECT_NAME}:2.0.0
    build: .
    command: sh -c "cd app && npm run start"
    volumes:
      - .:/app
    # ports:
    #  - 4443:${NODE_PORT}
    container_name: front-${PROJECT_NAME}
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/templates/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front
    container_name: nginx-${PROJECT_NAME}
    restart: unless-stopped
