name: publish

on:
  push:
    branches:
      - sarmad
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry

        uses: docker/login-action@v1

        with:
          registry: ghcr.io

          username: ${{ github.actor }}

          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build the hello-docker Docker image

        run: |

          docker build . --tag ghcr.io/chatcrm/bizgpt-frontend-2_0:sarmad

          docker run ghcr.io/chatcrm/bizgpt-frontend-2_0:sarmad

          docker push ghcr.io/chatcrm/bizgpt-frontend-2_0:sarmad
